name: Docker Build and Push

on: 
  push:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v5
      - 
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_GHCR }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tinyproxy-docker:latest
      -
        name: Cleanup old versions
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'tinyproxy-docker'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
